service: translate-me-landing-page

provider:
  name: aws
  region: eu-west-2
  runtime: nodejs12.x

plugins:
  - serverless-finch
  - serverless-dotenv-plugin

custom:
  client:
    bucketName: ${env:bucketName}
    distributionFolder: dist
    errorDocument: index.html